### ISSUE TITLE
Machine guns shoot tracers

### ISSUE THREAD

**Issue by Joshua260403** [djog/djog_unos_2019#103]
Machine guns should shoot tracers:
 * Make machine guns fire red tracers for now
 * Machine gun ammo belts have a four-to-one tracers pattern, this means that every fifth bullet is a tracer: `. . . . | . . . . | . . . . | . . . . | . . . .` where `|` is a tracer.
 * Tracers should be bright lines on the screen (no smoke or whatever, see [video](https://www.youtube.com/watch?v=PzlvF--6bPI) **Video shows real military shooting M2HB into the distance, no gore or violence is visible**)

**Comment by Rijk-van-Putten** [comment]
We should have a trail/line renderer and shader first

**Comment by Rijk-van-Putten** [comment]
@Joshua260403 Do you mean the machine gun @robkruger or the new machine gun for the player in isuue #99??

**Comment by Joshua260403** [comment]
Machine guns in general always shot tracers
