### ISSUE TITLE
Reminder: present tomorrow/Friday at 18:15/18:45

### ISSUE THREAD

**Issue by richelbilderbeek** [djog/djog_unos_2019#112]
Dear Team Octane,

Tomorrow there are the DJO presentations. I need Team Octane to show off their work.

 * 18:15: one person with a laptop: check if the game works on the beamer
 * 18:45: the Team [1] is around at DJO before the presentations
 * approx 19:30: the Team [1] presents their work
 * approx 20:00: the Team [1] evaluates the course
 * after that: the Team is welcome until 22:00, but may choose to leave early

Hope to see most of you tomorrow :+1:

 * [1] that can be there and wants to be there

**Comment by Rijk-van-Putten** [comment]
I'll be there arround 18:45

**Comment by Joshua260403** [comment]
I'm not sure of I can be there in time

**Comment by AramPetiet** [comment]
I can be there at 18:15

**Comment by janderkkotlarski** [comment]
I will be present at 18:45.

**Comment by richelbilderbeek** [comment]
Well done! I've asked a couple of kids: yours was the favorite presentation.

Some Dutch quotes, from two different kids:

> "Ze werkten naar een duidelijk doel toe"
> "Ze werkten goed samen"

Closing this Issue :+1:
