### ISSUE TITLE
GAMEDESIGN: Brainstorm about the game

### ISSUE THREAD

**Issue by RafayelGardishyan** [djog/djog_unos_2019#17]
Brainstorm about the game with 2 or more people and make decisions.

(Rafayel will make a simple animated video with the game demo to demonstrate the idea)

**Comment by Joshua260403** [comment]
Im pretty sure we already decided on what the game is going to be...
What is this for?

**Comment by richelbilderbeek** [comment]
One month old, let's close it :+1:
