### ISSUE TITLE
VOTE: Do we want to use Patreon

### ISSUE THREAD

**Issue by RafayelGardishyan** [djog/djog_unos_2019#19]
Hi everyone,

If we want financial support, we can do it by starting a crowdfunding page. The easiest way to do this is by using Patreon.

Next week, 19 September @ 20:00 we're going to vote is we are going to use this service.

Bye

**Comment by richelbilderbeek** [comment]
@RafayelGardishyan: what was the outcome of the vote?

**Comment by Rijk-van-Putten** [comment]
@richelbilderbeek I think the outcome was that we would decide later.
