### ISSUE TITLE
Assign formal team roles

### ISSUE THREAD

**Issue by richelbilderbeek** [djog/djog_unos_2019#21]
It's a good idea to write in the README what the team roles are and who fulfills these. Even I may forget otherwise :-)

Currently, all it says is:

Name|Website
----|-----
[Richel](https://github.com/richelbilderbeek) | [pirouette](https://github.com/richelbilderbeek/pirouette)
[Rafayel](https://github.com/RafayelGardishyan) | [E-mail](mailto:rgardishyan@gmail.com)
[Rijk](https://github.com/Rijk-van-Putten) | [website](https://rijkvanputten.000webhostapp.com/)
[Joshua](https://github.com/joshua260403) | [Discord](https://discord.gg/yrt5egv)
[Mart](https://github.com/martje127) | [no website](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

I would enjoy, to add the roles:

Name|Website|Role(s)
----|-----|---
[Richel](https://github.com/richelbilderbeek) | [pirouette](https://github.com/richelbilderbeek|Adult supervision

Roles are, among others:

 * Junior, medior and senior dev
 * Team leader: ensures people can work together fruitfully
 * Chairman: sets the rules of a meeting
 * Coordinator: ensures people know what to do

Feel free to add roles if needed.

**Comment by RafayelGardishyan** [comment]
I suggest for me to be a medior developer or a senior developer. Rijk to be senior, because he is one of the Java experts and as we have voted me to be the chairman

Joshua and Hans could be medior developers, Rob also
I think Mart could also be a medior en Bram and the other newbees be Junior Developers

**Comment by richelbilderbeek** [comment]
Great. Now to finish the Issue, put that into the README :+1:
