### ISSUE TITLE
FYI: join/help the tresinformal team

### ISSUE THREAD

**Issue by richelbilderbeek** [djog/djog_unos_2019#22]
The Groninger research unit TRES is working on [a C++ with SFML game](https://github.com/tresinformal/game), every two weeks (before the [keivrijdag](https://github.com/richelbilderbeek/keivrijdag)) from 17:00-19:00.

If needed, I will ask Team Octane for assistance. 

If true, then I will need an email from your parents agreeing on this.

**Comment by RafayelGardishyan** [comment]
I can on some dates. Ask me if you need help

**Comment by richelbilderbeek** [comment]
@RafayelGardishyan: thanks! I will!

**Comment by richelbilderbeek** [comment]
I polled the other team: you are all welcome
