### ISSUE TITLE
Write class for shell

### ISSUE THREAD

**Issue by richelbilderbeek** [djog/djog_unos_2019#33]
There needs be a class for a shell. Call it `shell`.

For starters, a shell has an x, y and angle. Write the class and test it.

**Comment by Joshua260403** [comment]
Tanks dont shoot rockets tanks shoot shells,please call it a shell if it
fires the big cannon and a bullet when it fires a machine gun

Op vr 4 okt. 2019 12:14 schreef Richel Bilderbeek <notifications@github.com

**Comment by Rijk-van-Putten** [comment]
Done a while ago
