### ISSUE TITLE
ABSENT AGAIN: me again

### ISSUE THREAD

**Issue by Joshua260403** [djog/djog_unos_2019#43]
Time wise its a bit harder for me to get there now i live in Meerstad.
Ill try to follow the project from home as much as i can but i definitely wont be able to be the person who knows everything about the project.

Note that i will be fact checking everything since i am the guy who reads military articles and study ww2

**Comment by richelbilderbeek** [comment]
Too bad, never move away from the City of Angels.

**Comment by richelbilderbeek** [comment]
@Joshua260403: I will create some can-do-from-home Issues to get your wisdom in our game.

For example, did you knew that tanks shoot shells, instead of bullet :grin: ?

**Comment by Joshua260403** [comment]
Good idea

Also,
Guns shoot bullets (except shotguns, they shoot shells, but not tank shells)
AT-guns shoot shells
Autocannons shoot cartridges
Rocket lauchers launch rockets
Planes sometimes shoot missles
Ground vehicles shoot missles

Op do 10 okt. 2019 23:17 schreef Richel Bilderbeek <notifications@github.com
