### ISSUE TITLE
IMPORTANT! : CREATE YOUR OWN BRANCH

### ISSUE THREAD

**Issue by RafayelGardishyan** [djog/djog_unos_2019#45]
Create your own branch to work on. Ask @richelbilderbeek for instructions.
This is important to keep the github clean
Nobody pushes to master. Pushing to develop is allowed but not preferred.
So just push to your own branch an ask @RafayelGardishyan or @Rijk-van-Putten or @Joshua260403 to merge your branch with develop and master

**Comment by janderkkotlarski** [comment]
Done!

**Comment by richelbilderbeek** [comment]
Next week, Oct 17th, we'll do git merging with the juniors, including the rule never to push to master as a junior.

**Comment by richelbilderbeek** [comment]
Enough for now, closing this Issue :+1:
