### ISSUE TITLE
FYI: option to join the tresinformal team

### ISSUE THREAD

**Issue by richelbilderbeek** [djog/djog_unos_2019#47]
The Groninger research unit TRES is working on [a C++ with SFML game](https://github.com/tresinformal/game), every two weeks (before the [keivrijdag](https://github.com/richelbilderbeek/keivrijdag)) from 17:00-19:00.

They allow new members, including Team Octane!

There are no costs and the meeting are not affiliated with anything. There will be people drinking some beer. There will be people that take a break to smoke.

If you want to join: great! But -I am sorry to say- I will need an email from a parent/guardian agreeing on this, just to save my butt.

**Comment by richelbilderbeek** [comment]
Unassign if you've read this :+1:

Will close Issue after Oct 31st 2019.

**Comment by Joshua260403** [comment]
Wait on what day is it

**Comment by richelbilderbeek** [comment]
Every two weeks on a Friday.

**Comment by richelbilderbeek** [comment]
* Mart is interested and parents agree
 * Rob is interested, need contact with parents

**Comment by richelbilderbeek** [comment]
They meet weekly now, continue this Issue at #63
