### ISSUE TITLE
ABSENCE: Im ill

### ISSUE THREAD

**Issue by Joshua260403** [djog/djog_unos_2019#49]
If someone could keep me updated that would be amazing.

**Comment by Joshua260403** [comment]
Also next week ill be on vacation

**Comment by richelbilderbeek** [comment]
@Joshua260403: first, get well soon!

Second, here's an update:

 * Rafayel is busy getting Travis to run
 * Rijk is busy separating the OpenGL graphics display from the game logic
 * Hans is making lots of Issues
 * Rob did some Issues
 * Bram and Mart practiced git branching

Third, you'd be welcome to join [https://github.com/tresinformal/game](https://github.com/tresinformal/game). I just need to know your parents agree, so send me their email adress or the other way around.

Hope to see you in two weeks, Richel
