### ISSUE TITLE
Battlegroud enviroment(s)

### ISSUE THREAD

**Issue by Hans-Bouwman** [djog/djog_unos_2019#51]
What should the setting(s) be for the tank battles?

Settings:
- grassland
- tundra
- desert

**Comment by robkruger** [comment]
I suggest we create maps, and for each setting we have a different map.

**Comment by martje127** [comment]
i could not find a pixel tudra from above, and witch biomes do i need to make more.

**Comment by richelbilderbeek** [comment]
Just use Google maps and search for 'tundra', e.g. [https://goo.gl/maps/HHUt7K8k2GVicpp67](https://goo.gl/maps/HHUt7K8k2GVicpp67)

**Comment by Joshua260403** [comment]
I cant remember the last time tanks battled in a tundra but ok

We defo need the following tho:
- [ ] snowy hills
- [ ] desert
- [ ] fields

**Comment by martje127** [comment]
i added snow mountains

**Comment by Rijk-van-Putten** [comment]
@martje127  Added 2 new backgrounds!
