### ISSUE TITLE
FYI: teach at Jimmy's in Appingedam

### ISSUE THREAD

**Issue by richelbilderbeek** [djog/djog_unos_2019#64]
Jimmy's is an institution aimed at older teenagers where you can ask all the question you've always wanted to know about drugs, parents, love, etc. Additionally, they organise cool activities!

There will be a workshop I will teach at Jimmy's in Appingedam, [Facebook event here](https://www.facebook.com/events/1191165741080350/):

![72752685_967588993611318_8707463137944666112_n](https://user-images.githubusercontent.com/2098230/67638613-c9018f80-f8e6-11e9-8a87-5210828817da.jpg)

I would enjoy having some Team Octane members with me. I plan to just do Processing, as this saves me time in preparing. If some teens want to take over, I'd be open for that :+1:

**Comment by Joshua260403** [comment]
Ik kan waarschijnlijk niet, 15 november is ook de open dag van de Universiteit Twente

**Comment by Joshua260403** [comment]
Nvm it is possible, but I might be a little late. I want to come

Op zo 27 okt. 2019 18:24 schreef Richel Bilderbeek <notifications@github.com

**Comment by richelbilderbeek** [comment]
You'd be welcome to join in any time. In case you're in doubt: I will pay your travel expenses!

At 17:30-18:30 will be -probably- pizza, want us to order one for you too?

**Comment by Joshua260403** [comment]
No need for pizza for me

**Comment by Rijk-van-Putten** [comment]
I don't know processing

**Comment by richelbilderbeek** [comment]
Processing, a Java dialect, is what I teach the 7-12 year old kids, see [Dutch material here](https://github.com/richelbilderbeek/processing_voor_jonge_tieners). I think one hour of preparation is enough for each Team Octane member to be able to teach. We could try it on any Friday :rainbow:

**Comment by richelbilderbeek** [comment]
Sent email to Joshua, Mart and Rafayel:

```
Hoi Joshua, Mart, Rafayel,

(ik heb Rob's email niet, iemand anders wel?)

Morgen/vrijdag pakken we (minus Joshua, die komt later) bus 6 om 16:15 op CS Groningen, halte J, naar Appingedam.

Daar is voedsel -geen pizza, ik had het fout gehoord- voor ons. Heb je dieetwensen, mail dan Ferdi: [...]

Tussen 19:00-21:00 hebben we negen deelnemers en gaan we Processing doen en veel stoere grappen maken :-)

Om 21:00 peren we 'm rustigjes. Wat rondhangen met de Appingedammer jeugd vind ik prima. Als 1 persoon wil vertrekken, dan doen we dat.

[...]
```

 * public email: info@jimmysdal.nl

**Comment by robkruger** [comment]
I can't, I'm still in Den Haag at 16:15

**Comment by robkruger** [comment]
My e-mail is either robkruger9@gmail.com or 4958@praedinius.nl

**Comment by Joshua260403** [comment]
I might be on time, I left Enschede at 15:00

**Comment by richelbilderbeek** [comment]
Want food? If yes, email Ferdi

**Comment by richelbilderbeek** [comment]
It has been done :+1:
