### ISSUE TITLE
How does one use Intellij IDEA to make the project work?

### ISSUE THREAD

**Issue by janderkkotlarski** [djog/djog_unos_2019#70]
I keep bumping into the same issues after finally getting java and IDEA installed, namely not knowing what files to put in what configuration file.
I still don't know whether I configured the libraries correctly and then getting the project to run is impossible, because the run button does not work.
I know I still have to add some file somewhere, but I forgot which exact file(s) and into what.
It would be handy to have some instructions on what to do when one has correctly configured the libraries.

**Comment by robkruger** [comment]
https://github.com/djog/djog_unos_2019/blob/rob/doc/configure_idea.md

**Comment by janderkkotlarski** [comment]
Do you work on Windows 7, Windows 10 or which Linux distro?
Because I tried do apply what you wrote down, but with no success.
I just can't get the last step to work, and I don't know whether I am doing something wrong, or the OS is playing tricks or whether I installed IDEA properly on my Windows 7 PC.

**Comment by robkruger** [comment]
I work on Windows 10

**Comment by janderkkotlarski** [comment]
I cannot select TankGame and I'm on Win 7.

**Comment by janderkkotlarski** [comment]
Also solved.
