### ISSUE TITLE
Player controls

### ISSUE THREAD

**Issue by Hans-Bouwman** [djog/djog_unos_2019#72]
I think everyone agrees that players will:
- Aim with the mouse.
- Move with WASD.

Move how exactly? Either:
- A & D to turn, W & S for forwards and backwards.
- WASD for north, west, south & east respectively.
- Or something else.

**Comment by Joshua260403** [comment]
I'd say A and D to steer
and W and S to move forwarda and backwards

We also could make the steering accurate, but ill need to explain more for that

**Comment by robkruger** [comment]
I agree with @Joshua260403 and will implement that for now
