### ISSUE TITLE
GLSL version

### ISSUE THREAD

**Issue by Hans-Bouwman** [djog/djog_unos_2019#73]
What GLSL version are we going to use?

**Comment by richelbilderbeek** [comment]
I notice on my rather up-to-date Lubuntu computer:

```
error: GLSL 4.40 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES
```

We should vote on a version that we all have.

**Comment by Rijk-van-Putten** [comment]
It depends on hardware, not software. we should use a version that works on all computers.

**Comment by Hans-Bouwman** [comment]
version 1.20 should work on all computers, see issue #87
