### ISSUE TITLE
Oh dear, i forgot

### ISSUE THREAD

**Issue by Joshua260403** [djog/djog_unos_2019#74]
Was too busy setting up my ethernet and reinstalling raspbian on my raspi

**Comment by Joshua260403** [comment]
will be there next week tho

also i can start work on a tech tree just assign me to an issue if i should

and assign me to any issue to fact check because historical accuracy is important

**Comment by richelbilderbeek** [comment]
Hmmm, it appears I read this a bit late :rainbow: 

See you this Thursday then :+1:
