### ISSUE TITLE
Merge conflict when merging develop into local branch.

### ISSUE THREAD

**Issue by janderkkotlarski** [djog/djog_unos_2019#75]
I'm encountering a merge conflict when merging develop into my local branch and it's driving me insane, because I have no interest solving merge conflicts between master and develop outside of my own local branch, because I assume I will have to solve this each and every time I want to keep my local branch updated.

What do?

**Comment by richelbilderbeek** [comment]
AFAIK, there are some difficulties with merging, due to the Java and IDEA setup.

I will assign medior @Rijk-van-Putten to help you out.

**Comment by janderkkotlarski** [comment]
Ugh, Java and IDEA spaghettios...

**Comment by richelbilderbeek** [comment]
It's part of the learning curve :rainbow: :+1:

**Comment by janderkkotlarski** [comment]
It' s clear now.
