### ISSUE TITLE
VOTE: Should we use "Maven"

### ISSUE THREAD

**Issue by RafayelGardishyan** [djog/djog_unos_2019#8]
Hi everyone,

@Rijk-van-Putten has suggested to use **Maven**. Maven is a build automation tool used primarily for Java projects. Maven addresses two aspects of building software: first, it describes how software is built, and second, it describes its dependencies. (source: [Wikipedia](https://en.wikipedia.org/wiki/Apache_Maven))

Research it for yourself and in a week (12 September) at 20:00 we are going to vote is we're going to use that.

Regards,
[Rafayel G.](https://github.com/RafayelGardishyan)

**Comment by Rijk-van-Putten** [comment]
Its hard to use multiple IDE's without using something like Maven or Gradle. Its only a bit harder to set up. I have tried installing maven and it worked fine for me in a few minutes.

**Comment by Joshua260403** [comment]
I dont think we should because i dont see the need and i can compile java
just fine with `javac`

Op za 7 sep. 2019 11:59 schreef Rijk van Putten <notifications@github.com>:

**Comment by richelbilderbeek** [comment]
What was the result?

**Comment by richelbilderbeek** [comment]
Ah, I see at #14 we voted against Maven :rainbow:
