### ISSUE TITLE
Add Tank to tech tree

### ISSUE THREAD

**Issue by richelbilderbeek** [djog/djog_unos_2019#82]
When I Duck for 'My Little Pony Tech Tree Tank' I find [Tank](https://mlp.fandom.com/wiki/Tank). This concludes that Tank should be added to the tech tree.

![Tank_flying_around_S2E7](https://user-images.githubusercontent.com/2098230/68421286-3e4e4980-019e-11ea-86a9-1351057461a9.png)

**Comment by Joshua260403** [comment]
This one doesn't have a gun, so it won't be strong enough. However, we could add a different kind of [tortoise](https://en.wikipedia.org/wiki/Tortoise_heavy_assault_tank)

**Comment by richelbilderbeek** [comment]
Let's see what happen and prioritize *even more important* things for now :+1:
