### ISSUE TITLE
The turret should rotate at a certain speed, instead of the almost teleporting it does now

### ISSUE THREAD

**Issue by robkruger** [djog/djog_unos_2019#84]
Currently, the turret almost teleports to rotate to the mouse. In reality, it has a maximum speed. Implement that.

**Comment by Rijk-van-Putten** [comment]
@robkruger  You broke the shooting system. please fix

**Comment by robkruger** [comment]
Works fine for me?

**Comment by Rijk-van-Putten** [comment]
@robkruger I discovered I works fine in the first 360 degrees. But if you rotate more than that it doesn't.

**Comment by Rijk-van-Putten** [comment]
@robkruger If it works well on your PC then you can leave it as it is now and I will create an issue.
Thanks for sending the video.

**Comment by robkruger** [comment]
Ah, I see it. It's broken while moving

**Comment by Rijk-van-Putten** [comment]
Its working again
