### ISSUE TITLE
Create a gun switching system

### ISSUE THREAD

**Issue by Rijk-van-Putten** [djog/djog_unos_2019#98]
The player should be able to switch guns with the arrow keys. Make a system that does that.
The default gun should be accessed with 1, the second gun with 2, etc.

**Comment by Joshua260403** [comment]
Now hold on there, have you ever seen a tank with more than one gun (apart from the m3 lee).

**Comment by Joshua260403** [comment]
I think it would make more sense to have it be a shell switch system.
