### ISSUE TITLE
Create a machine gun

### ISSUE THREAD

**Issue by Rijk-van-Putten** [djog/djog_unos_2019#99]
Right now the tank can only shoot shells. Create an other type of gun, an machine gun. The machine gun should be selected with the 2 key. The machine gun should also fire much faster & should have another texture.

**Comment by robkruger** [comment]
If you have found another texture, also apply it to the machine gun nests.

**Comment by Joshua260403** [comment]
Im not sure about the 2 key, would make more sense to have 2 select a different kind of shell....

**Comment by Rijk-van-Putten** [comment]
Implemented it with 2 line of code 😄

**Comment by Rijk-van-Putten** [comment]
merged
